const Reducers = {
    //Adding article reducer constants
    ADD_ARTICLE_LOADING: "ADD_ARTICLE_LOADING",
    ADD_ARTICLE_LOADED: "ADD_ARTICLE_LOADED",
    ADD_ARTICLE_ERROR: "ADD_ARTICLE_ERROR",

    //getting all articles reducer constants
    GET_ALL_ARTICLES_LOADING: "GET_ALL_ARTICLES_LOADING",
    GET_ALL_ARTICLES_LOADED: "GET_ALL_ARTICLES_LOADED",
    GET_ALL_ARTICLES_ERROR: "GET_ALL_ARTICLES_ERROR"
};

export default Reducers;